layout_spectrum: 0.9274973
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8511979337781668
  brandStrength: 0.7305301951710135
  lightness: 0.07671184069477022
  brandColors:
    - '#C2C2A8'
    - '#14143A'
    - '#FCFCE0'
    - '#8C7D6A'
    - '#02FEE5'
  rhythmicContrast: 0.931168154347688
typography_spectrum: 0.3799897122662514
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: hessuj
