name: hessuj
favicon: null
layout_spectrum: 0.6460481495596468
typography_spectrum: 0.37998971226625144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7305301951710135
  lightness: 0.07671184069477022
  saturation: 0.8511979337781668
  rhythmicContrast: 0.931168154347688
purpose: []
